### ISSUE TITLE
Copy command should have the ability to write to a block device

### ISSUE THREAD

**Issue by Razaloc** [collabora/bmap-rs#11]
Currently, copying to a block device fails:

```
Found bmap file: Fedora-Server-36-1.5.aarch64.raw.bmap
Error: Failed to truncate file

Caused by:
    EINVAL: Invalid argument
```

**Comment by obbardc** [comment]
Instead of SD card device, please change to block device :-)

**Comment by obbardc** [comment]
The solution here would be to only call `ftruncate` if the destination is a regular file
