### ISSUE TITLE
Add final file/device sync and verification into bmap::copy

### ISSUE THREAD

**Issue by Razaloc** [collabora/bmap-rs#25]
Copy should also check if the resulting target and the source are being equals at the end, also compare their bmap files would be a way of verification

**Comment by Razaloc** [comment]
The verification may need to check first the kind of source (file / path / compressed file) copied and target (file / block device) to do a proper comparative.

**Comment by sjoerdsimons** [comment]
bmap::copy definitely shouldn't be doing this. What is your goal/use-case here? It may still be a reasonably use-case the suggested fix is however not

**Comment by obbardc** [comment]
The goal here was to simply check if `bmap::copy` was actually verifying what was written was, well, written against the checksums in the bmap file.

From code analysis, it turns out that is implemented, so we can close this issue.
