### ISSUE TITLE
CI: part or all actions-rs unmaintained

### ISSUE THREAD

**Issue by Razaloc** [collabora/bmap-rs#56]
**actions-rs/toolchain** seems to be [unmaintained](https://github.com/actions-rs/toolchain/issues/216). Something similar with **actions-rs/cargo** We use it and at some point part of it will be deprecated; we need to make it compatible with Node.js 16. CI raise this warning: 

```Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: actions-rs/toolchain@v1, actions-rs/cargo@v1```

Also:
```The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/```

**Comment by Razaloc** [comment]
This issue might be relevant for other projects, also using `actions-rs/toolchain` and `actions-rs/cargo`: 
[lava-api](https://github.com/collabora/lava-api/blob/main/.github/workflows/ci.yml)
[lava-gitlab-runner](https://github.com/collabora/lava-gitlab-runner/blob/main/.github/workflows/ci.yml)
[gitlab-runner-rs](https://github.com/collabora/gitlab-runner-rs/blob/main/.github/workflows/ci.yml)
[obs-gitlab-runner](https://github.com/collabora/obs-gitlab-runner/blob/main/.github/workflows/ci.yml)
[open-build-service-rs](https://github.com/collabora/open-build-service-rs/blob/main/.github/workflows/ci.yml)
[hawkbit-rs](https://github.com/collabora/hawkbit-rs/blob/main/.github/workflows/ci.yml)
If this patch turns out to solve the problem I could apply the same solution to the others

**Comment by Razaloc** [comment]
[Version 1.1.0 uses Node16 (instead of Node12)](https://github.com/actions-rs/cargo/pull/223)
[Update the action to run on Node 16](https://github.com/actions-rs/toolchain/pull/220)
This two PRs should solve the warnings, in that case we wouldn't need #57

**Comment by obbardc** [comment]
This is covered at https://github.com/actions-rs/toolchain/issues/216 ; I have subscribed to that.

**Comment by sjoerdsimons** [comment]
fwiw for my other crates i've moved to https://github.com/dtolnay/rust-toolchain
